### ISSUE TITLE
uninitialized constant Haml::Rails::Railtie::SourceAnnotationExtractor (NameError)

### ISSUE THREAD

**Issue by chiperific** [haml/haml-rails#176]
I get this error when starting a development server.
Is this a known bug?
Removing bootsnap and spring does not fix the issue.
Uninstalling and re-installing haml and haml-rails does not fix the issue.
Reverting to Ruby 2.7.0 does not fix the issue.

### Partial stack trace:
```
5: from /Users/ckragt/.rvm/gems/ruby-2.7.2/gems/railties-6.1.0/lib/rails/initializable.rb:32:in `instance_exec'
	 4: from /Users/ckragt/.rvm/gems/ruby-2.7.2/gems/haml-rails-1.0.0/lib/haml-rails.rb:49:in `block in <class:Railtie>'
	 3: from /Users/ckragt/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	 2: from /Users/ckragt/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
	 1: from /Users/ckragt/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
/Users/ckragt/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant Haml::Rails::Railtie::SourceAnnotationExtractor (NameError)
```

### Env:
Ruby 2.7.2
Rails 6.1.0
haml (5.2.1)
haml-rails (1.0.0)
haml_lint (0.36.0) (not sure this is applicable, but...)
bootsnap (1.5.1)
spring (2.1.1)

**Comment by chiperific** [comment]
This is an issue with haml-rails 1.0, I should have checked to make sure I was using the latest gem. Apologies.
