### ISSUE TITLE
No error checking in `haml:erb2haml` task

### ISSUE THREAD

**Issue by dirschn** [haml/haml-rails#193]
I ran the `haml:erb2haml` task after running `gem install html2haml`, and apparently `html2haml` didn't install properly. The task reported that it couldn't find it for each file, yet at the end it acted as though the task completed  successfully and asked whether I wanted to delete the original files. I said yes, because this was an unimportant brand new project, and after the task was done all of my views were erased because none of the ones it said were generated actually were generated.

It seems like there could be some checking in the script to at least verify the expected files exist before reporting a success? I'd be happy to take a crack at it, but I'm a little surprised no one else has reported this yet.

```
rails haml:erb2haml 
--------------------------------------------------------------------------------
Generating HAML for app/views/default/pages/homepage.html.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
Generating HAML for app/views/default/pages/show.html.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
Generating HAML for app/views/default/shared/_navigation.html.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
Generating HAML for app/views/layouts/application.html.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
Generating HAML for app/views/layouts/default/application.html.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
Generating HAML for app/views/layouts/mailer.html.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
Generating HAML for app/views/layouts/mailer.text.erb...
/home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable html2haml for gem html2haml. html2haml is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /home/nick/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /home/nick/.rbenv/versions/3.2.2/bin/html2haml:25:in `<main>'
--------------------------------------------------------------------------------
HAML generated for the following files:
        app/views/default/pages/homepage.html.erb
        app/views/default/pages/show.html.erb
        app/views/default/shared/_navigation.html.erb
        app/views/layouts/application.html.erb
        app/views/layouts/default/application.html.erb
        app/views/layouts/mailer.html.erb
        app/views/layouts/mailer.text.erb
--------------------------------------------------------------------------------
Would you like to delete the original .erb files? (This is not recommended unless you are under version control.) (y/n)
y
Deleting original .erb files.
--------------------------------------------------------------------------------
Task complete!
```

**Comment by chmich** [comment]
Same here: no .haml file was created and after deleting the original files all views are gone (i done this on a new test project, a real project would be destroyed by that function!)

**Comment by dirschn** [comment]
Honestly I forgot about this. I'll look into it and make a PR sometime this week

**Comment by dirschn** [comment]
@chmich I had a stroke of inspiration, check out #195 and let me know if it works for your case.

**Comment by chmich** [comment]
@dirschn Thanks, sounds good! 

How about the idea moving all original files into a backup-folder (e.g. «view_backups_20250430»)? Then you may not need to ask if theese files should be destroyed.

I will write a version for that for my gem (svelte-on-rails). for that i copied out your rake task (erb2haml) and will add this improvements. I will leave you a copy of that when it ist tested, i think this week.

**Comment by dirschn** [comment]
@chmich Quick disclaimer, I'm not a maintainer here or anything, just a random schmuck who noticed an issue and wanted to fix it. That said, I thought about your suggestion and I keep coming back to thinking it's unnecessary. That kind of thing can be solved by either using version control or choosing not to delete and backing them up yourself. 

Again, I'm not a maintainer and if one of those fine folks likes the idea I'd be happy to implement it here!

**Comment by chmich** [comment]
@dirschn I agree with you that a backup folder is unneccesary because of VCS. But for the thinking of a 100% sure process i prefer a way that is independet and sure. And, on the other hand, When all views are backed up in one folder, it is one click to delete this folder. So, i decided for this way. So, my task is:

```ruby
  def self.install_haml_and_convert

      gu = SvelteOnRails::GemUtils
      gu.install_gem('haml-rails')
      gu.install_gem('html2haml', group: :development)

      # check existing files

      existing_haml_files = Dir.glob('app/views/**/*.haml').select { |f| File.file? f }

      overwrite_files = []
      files = Dir.glob('app/views/**/*.html.erb').each_with_object([]) do |f, ary|
        new_file = f.gsub(/\.erb\z/, '.haml')
        if File.file? new_file
          overwrite_files += [new_file]
          existing_haml_files.delete(new_file)
        end
        if File.file? f
          ary << [
            f,
            new_file
          ]
        end
      end

      if files.empty?
        puts "No .erb files found. Task will now exit."
        exit
      end

      # ask if haml already exist

      if existing_haml_files.any?
        puts '-' * 80
        begin
          puts "Theare are already .haml files:"
          puts existing_haml_files
          puts "Would you like to continue? (y/n)"
          continue = STDIN.gets.chomp.downcase[0]
        end until ['y', 'n'].include?(continue)
        if continue == 'n'
          puts 'skipping convert to haml'
          exit
        end
      end

      # ask if overwrite

      if overwrite_files.any?
        puts '-' * 80
        begin
          puts "The following files already exist and would be overwritten:"
          puts overwrite_files
          puts "Would you like to overwrite these .haml files? (y/n)"
          should_overwrite = STDIN.gets.chomp.downcase[0]
        end until ['y', 'n'].include?(should_overwrite)
      end

      puts '-' * 80

      # convert

      backup_dir = "svelte_on_rails_backup_views_#{Time.now.strftime('%Y%m%d_%H%M%S')}"
      FileUtils.mkdir_p(backup_dir)

      Dir.chdir(Rails.root) do
        files.each do |f|
          stdout, stderr, status = Open3.capture3("html2haml #{f.join(' ')}")
          if stderr.present?
            raise stderr
          else
            view_dir = File.dirname(f.first).to_s.match(/(?<=app\/views\/)(.*)/).to_s
            backup_view_dir = backup_dir + '/' + view_dir
            FileUtils.mkdir_p(backup_view_dir)
            FileUtils.mv(f.first, backup_view_dir)
            puts "Converted #{f.join(' => ')}"
          end
        end
      end

    end
  end
```

**Comment by dirschn** [comment]
Oh, very cool! I haven't heard of that. My intention here was to make as small of a change as possible to what's existing, but maybe I'll make a follow-up PR with a clean up of the whole task!

**Comment by chmich** [comment]
Thank you, @dirschn! But the better place for this task might be the `haml2rails` gem?

And for the safety of the whole process: Like you, I did my test on an empty rails project. But on an existing project with many views, restoring them all from VCS can be a lot of work! You could leave a hint like Do not forget to commit before running this task ... but you know ... we are all human ... mistakes happen :)

**Comment by dirschn** [comment]
@chmich That's a good point, personally I hate writing HTML and HAML is the first thing I do in a Rails project, but I forget that some folks could switch an established project. I think I'll restructure my PR a little now, and incorporate some of what you've suggested here. Thanks for the suggestions!

**Comment by chmich** [comment]
I think i know what the error was on my case:

On the original script there is a line where `html2haml ...` is just wrapped within backticks! But without the gem `html2haml` installed (i am not sure but i think this was the case for me yesterday) ... this line does nothing, and no file is converted and no error is raised!. But, then, if you accept `delete original files` you end up by destroying all views. Not 100% sure but i assume this is solved by my approach above (Open3 and then raise if stderr.present?)

**Comment by dirschn** [comment]
> I think i know what the error was on my case:
> 
> On the original script there is a line where `html2haml ...` is just wrapped within backticks! But without the gem `html2haml` installed (i am not sure but i think this was the case for me yesterday) ... this line does nothing, and no file is converted and no error is raised!. But, then, if you accept `delete original files` you end up by destroying all views. Not 100% sure but i assume this is solved by my approach above (Open3 and then raise if stderr.present?)

Yup, this is the same issue I had. My solution here solves it as well, but I'm certainly interested in making it more robust. I'll take a second crack at it in the next day or two

**Comment by chmich** [comment]
I noticed this on [html2erb](https://github.com/haml/html2haml/issues/96)

**Comment by chmich** [comment]
I have now removed my code block on [my answer above](https://github.com/haml/haml-rails/issues/193#issuecomment-2841775373) and replaced it with the link to the repository.

I think this is now the correct installer to copy and paste into this gem or for a PR.

I highly recommend this to the maintainers of this project, as the current task is super dangerous!

That one gem adds and removes another gem is a unusual aproach! But this is the purpose: The `htm2ham` gem is only needed once and then never again on a certain app. Theoretically, it would be enough to install with `gem install html2haml` to make the conversion work. But to make sure it runs stable in a rails app, the surest way is to add it to the gemfile and remove it after the process has run through! This is what my task does.

In my case, this is a really heavy installer, where haml is just one part of more. But I wanted to have a good developer acceptance of these many necessary installation steps, so I invested a lot of time in making a safe running process. But the Haml part (link above) should serve exactly the same purpose as it is needed here. 

So, my need now is solved, but, as a Haml fan, like @dirschn, i would be happy to see these features here on `haml-rails`.

**Comment by dirschn** [comment]
@chmich Thanks for all that! I'll take a look at it, if I have any notes or questions do you have any preference how I get them to you? I can open an issue in your repo to keep this one a little cleaner

**Comment by chmich** [comment]
Yes, please, @dirschn if you have questions or issues or ideas please leave it on my repo and we can develop there. The haml task (intalling both gems and execute the conversion) is within a separated module.
